---
title: Kutatás
date: '2018-08-18'
slug: research
output: blogdown::html_page
---

##A zöngeképzés vizsgálata számítógépes játékkal elicitált emocionális megnyilatkozásokban

A kísérlet célja annak a vizsgálata, hogy milyen reakciómintázatok jelennek meg a beszédképzésben, azon belül is a hangszalagok működésében különböző érzelmi hatást kiváltó ingerek megtapasztalása esetén. Az értékelési érzelemelméleti modellek szerint a megtapasztalt ingerek kognitív kiértékelése határozza meg a különböző viselkedésbeli és fiziológiai reakciómintázatokat, így a beszédben végbemenő változásokat is. Vizsgálatomban olyan érzelmi állapotok hatását vizsgálom, amelyek a két ilyen értékelési lépés dimenziója mentén különböznek: elemzem a várt, illetve váratlan ingerek, illetve az egyén céljaihoz hozzájáruló, vagy azt hátráltató események hatását, és az ezek közti eltéréseket. Ezeket az érzelmi állapotokat egy számítógépes játék különböző játékeseményei alatt vizsgálom, mégpedig a játék irányítására szolgáló hangutasítások elemzésével.

##Érzelmi állapotok szándékolt kifejezése a zöngeképzés szempontjából

Kutatásomban a magyar á mondatszó megvalósulásait vizsgáltam. A vizsgálat fő kérdése az volt, hogy mutat-e eltéréseket az indulatszó fonációjának típusa és alapfrekvenciája annak függvényében, hogy milyen érzelmet fejez ki a beszélő. Elemeztem egyrészt a az egyes fonációtípusok gyakoriságát a kifejezett érzelem függvényében, másrészt azokban az indulatszókban, ahol fonációtípus-váltást tapasztaltam, vizsgáltam a különböző fonációtípusok sorrendiségének jellemző mintázatait. Kitértem a nemek közötti eltérésekre is. Az spektrogram és oszcillogram vizuális inspekciója során megállapított fonációtípusokat elektroglottografikus artikulációs adatokkal vetettem össze. Vizsgáltam az érzelmek hatását a zönge alapfrekvenciájára is. A mért artikulációs és akusztikai paramétereken főkomponens-elemzést végeztem annak megállapítására, vajon az általam alkalmazott érzelemelméleti modell (Russel 1980) dimenziói magyarázzák-e az adatok varianciáját.

##Az irreguláris fonáció variabilitása magyar beszélőknél

A fonációtípusok a gégeizmok különböző beállításai révén létrejövő eltérő rezgésmódok. Az irreguláris zönge képzésekor Laver (1980) szerint a hangajkak mediális kompressziója nagy-, míg longitudinális feszítettségük kismértékű. A nagymértékű mediális kompresszió következménye, hogy a tüdőből kiáramló levegő csak ritkábban, és nem feltétlenül szabályos időközönként tudja szétfeszíteni az egymásnak feszülő hangajkakat, tehát a zönge alapfrekvenciája a modális zönge esetében mérhetőnél alacsonyabb lesz, az egymást követő glottális ciklusok periódusidejében pedig nagymértékű variabilitás figyelhető meg. Ugyanakkor ez a fonációs mód számos, a fentebbiekben leírt prototipikus irreguláris fonációtól eltérő formában is megjelenhet. Az itt bemutatott kutatás célja annak vizsgálata, hogy az irreguláris fonáció Keating et al. (2015) által meghatározott altípusai milyen gyakorisággal jelennek meg magyar beszédben az /ɒ/ magánhangzóban. Az altípusok gyakoriságát a beszélők nemének függvényében is elemzem, így árnyalva a fonációtípusok és a beszélő neme közötti összefüggésekről rendelkezésünkre álló ismeretanyagot.